// Code generated by protoc-gen-orzkratos-errors (errgenkratos). DO NOT EDIT.

package article

import (
	errors "github.com/go-kratos/kratos/v2/errors"
	newerk "github.com/yylego/kratos-errors/errorskratos/newerk"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUnknown(err error) bool {
	return newerk.IsError(err, ErrorReason_UNKNOWN, 500)
}

func ErrorUnknown(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_UNKNOWN, format, args...)
}
func IsBadParam(err error) bool {
	return newerk.IsError(err, ErrorReason_BAD_PARAM, 400)
}

func ErrorBadParam(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(400, ErrorReason_BAD_PARAM, format, args...)
}
func IsArticleNotFound(err error) bool {
	return newerk.IsError(err, ErrorReason_ARTICLE_NOT_FOUND, 404)
}

func ErrorArticleNotFound(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(404, ErrorReason_ARTICLE_NOT_FOUND, format, args...)
}
func IsServerError(err error) bool {
	return newerk.IsError(err, ErrorReason_SERVER_ERROR, 500)
}

func ErrorServerError(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_SERVER_ERROR, format, args...)
}
func IsDbError(err error) bool {
	return newerk.IsError(err, ErrorReason_DB_ERROR, 500)
}

func ErrorDbError(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_DB_ERROR, format, args...)
}
func IsTxError(err error) bool {
	return newerk.IsError(err, ErrorReason_TX_ERROR, 500)
}

func ErrorTxError(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_TX_ERROR, format, args...)
}
func IsArticleCreateFailure(err error) bool {
	return newerk.IsError(err, ErrorReason_ARTICLE_CREATE_FAILURE, 500)
}

func ErrorArticleCreateFailure(format string, args ...interface{}) *errors.Error {
	return newerk.NewError(500, ErrorReason_ARTICLE_CREATE_FAILURE, format, args...)
}
